export const PASSWORD_LIST_REQUEST = 'PASSWORD_LIST_REQUEST';
export const PASSWORD_LIST_SUCCESS = 'PASSWORD_LIST_SUCCESS';
export const PASSWORD_LIST_FAIL = 'PASSWORD_LIST_FAIL';

export const PASSWORD_SAVE_REQUEST = 'PASSWORD_SAVE_REQUEST';
export const PASSWORD_SAVE_SUCCESS = 'PASSWORD_SAVE_SUCCESS';
export const PASSWORD_SAVE_FAIL = 'PASSWORD_SAVE_FAIL';

export const PASSWORD_DELETE_REQUEST = 'PASSWORD_DELETE_REQUEST';
export const PASSWORD_DELETE_SUCCESS = 'PASSWORD_DELETE_SUCCESS';
export const PASSWORD_DELETE_FAIL = 'PASSWORD_DELETE_FAIL';

export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_FAIL = 'PASSWORD_UPDATE_FAIL';